spring:
  application:
    name: Mo-ITZY
  datasource:
    url: jdbc:mysql://localhost:3306/test?maxAllowedPacket=10000000&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true # DB URL
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver # DB Driver
  jpa:
    hibernate:
      ddl-auto: update # create, update, validate, none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug